services:
  - type: web
    name: e-waste-facility-locator
    env: python
    runtime: python-3.11.9
    region: oregon
    plan: free
    branch: main
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt && python manage.py collectstatic --no-input --clear && python manage.py migrate --noinput"
    startCommand: "gunicorn blogs.wsgi:application --log-file -"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        sync: false
